### numpy

* numpy is a python library used for working with arrays
* numpy stands for numerical python
* It has functions to work with linear algebra, fourier transform and matrices
* created in 2005 b y travis oliphant
* open source

### why numpy?

* less memory
* less time taking (faster)

In [2]:
import numpy
numpy.__version__

'1.18.1'

In [3]:
import numpy as np
a=np.array([10,20,30,40])  #creating an array

In [5]:
print(type(a))
print(a.ndim)  #no of dimensions
print(a.dtype) #data type of array
print(a.shape) #shape of array as a tuple
print(a.size)  #size of an array
print(a.itemsize)  #each element size in bytes

<class 'numpy.ndarray'>
1
int32
(4,)
4
4


In [6]:
a=np.array([1,2,3,4],np.int8)
a.dtype

dtype('int8')

In [7]:
a.itemsize

1

In [8]:
2**8-1

255

In [9]:
a=np.array([1,2,3,4,512],np.int8)
print(a)

[1 2 3 4 0]


In [10]:
a=np.array([2,3,4,6.7,8.4])
print(a.dtype)
print(a)

float64
[2.  3.  4.  6.7 8.4]


In [11]:
a=np.array([2,3,8.1,"sai"])
a.dtype

dtype('<U32')

In [12]:
dir(numpy.dtype)

['__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'alignment',
 'base',
 'byteorder',
 'char',
 'descr',
 'fields',
 'flags',
 'hasobject',
 'isalignedstruct',
 'isbuiltin',
 'isnative',
 'itemsize',
 'kind',
 'metadata',
 'name',
 'names',
 'ndim',
 'newbyteorder',
 'num',
 'shape',
 'str',
 'subdtype',
 'type']

In [17]:
l1=[1,2,3]
l2=[4,5,6]
a=np.array((l1,l2))  #2D array
print(a)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
2


In [18]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [20]:
a=np.array(range(9))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
print(np.arange(11,21))
print(np.arange(5))
print(np.arange(4,1))
print(np.arange(1,10))

[11 12 13 14 15 16 17 18 19 20]
[0 1 2 3 4]
[]
[1 2 3 4 5 6 7 8 9]


In [23]:
a=np.arange(11,21)
print(type(a))

<class 'numpy.ndarray'>


In [24]:
print(np.linspace(1,10,4)) #last parameter is no of elements

[ 1.  4.  7. 10.]


In [25]:
print(np.linspace(1,10,3)) #start , stop value , 

[ 1.   5.5 10. ]


### Array Initialization

In [30]:
a=np.ones((3,2,1),np.int)
print(a)
print(a.ndim)

[[[1]
  [1]]

 [[1]
  [1]]

 [[1]
  [1]]]
3


In [31]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [34]:
print(np.zeros((1)))  #1D array
print(np.zeros((1,2))) #2D array

[0.]
[[0. 0.]]


In [35]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values to

In [40]:
np.full((3,2),9) #creates an array with given shape and type, fill with fill value

array([[9, 9],
       [9, 9],
       [9, 9]])

In [41]:
help(np.eye)

Help on function eye in module numpy:

eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    order : {'C', 'F'}, optional
        Whether the output should be stored in row-major (C-style) or
        column-major (Fortran-style) order in memory.
    
        .. versionadded:: 1.14.0
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    -

In [44]:
a=np.eye(4)
print(a)
print(a.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2


In [45]:
np.diag([3,5,7,8])

array([[3, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 8]])

### random

In [50]:
print(np.random.randint(10))  #random value in a given range
print(np.random.randint(10,100,10)) #start,stop,shape
print(np.random.randint(10,100,(2,3)))

5
[50 62 90 51 21 15 15 27 69 11]
[[18 36 45]
 [93 47 57]]


In [51]:
print(np.random.rand(2,3))

[[0.52179806 0.3436747  0.36934238]
 [0.92441703 0.14854173 0.7767948 ]]


In [52]:
print(np.random.normal())

-1.1895184698347765


In [53]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : fl

In [54]:
np.random.randn()

0.13325523588131

In [55]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)
    
    Return a sample (or samples) from the "standard normal" distribution.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    .. note::
        New code should use the ``standard_normal`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.
    
    Paramete

In [56]:
np.random.randn(2,3)

array([[ 0.61673301, -2.03657143,  0.81413581],
       [ 0.54347592, -0.34051801, -1.7387462 ]])

### indexing slicing and subsetting

In [60]:
a=np.arange(25)
print(a[:])
print(a[1:20:2])
print(a[20:])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 1  3  5  7  9 11 13 15 17 19]
[20 21 22 23 24]


In [61]:
a[[0,3,5]]

array([0, 3, 5])

In [63]:
a=np.arange(25)
a.ndim

1

In [64]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
b=np.arange(25).reshape(4,5)

ValueError: cannot reshape array of size 25 into shape (4,5)

In [71]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [72]:
a[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [73]:
a[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [74]:
a[1:4:2]  #row with index 1 ,3

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [75]:
a[[1,2,4]] #row with index 1,2 and 4

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [76]:
a[3][4]

19

In [77]:
a[3,4]

19

In [78]:
a=np.array([10,20,30])
for i in a:
    print(i)

10
20
30


In [80]:
a2=np.arange(8).reshape(4,2)
print(a2)
for i in a2:
    print(i)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[0 1]
[2 3]
[4 5]
[6 7]


### stacking
* hstack
* vstack

In [82]:
help(np.hstack)

Help on function hstack in module numpy:

hstack(tup)
    Stack arrays in sequence horizontally (column wise).
    
    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.
    
    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.
    
    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length.
    
    Returns
    -------
    stacked : ndarray
        The array formed by stacking the given arrays.
    
    See Also
    --------
    stack : Join a sequence of arrays along a new axis.
    vstack : Stac

In [85]:
a=np.array((1,2,3))
b=np.array((4,5,6))
np.hstack((a,b))  #horizontal stack

array([1, 2, 3, 4, 5, 6])

In [87]:
a=np.array([[1],[2],[3]])
b=np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [89]:
b1=np.random.randint(1,10,(2,2))
b2=np.random.randint(1,10,(2))
print(b1)
print(b2)
np.vstack((b1,b2)) #vertical stack ,will add rows

[[4 6]
 [6 1]]
[6 7]


array([[4, 6],
       [6, 1],
       [6, 7]])

In [90]:
b3=np.random.randint(1,10,(2,1))
print(b1)
print(b3)
np.hstack((b1,b3)) #will add columns

[[4 6]
 [6 1]]
[[1]
 [4]]


array([[4, 6, 1],
       [6, 1, 4]])

### fancy indexing or boolean indexing

In [91]:
a=np.random.randint(1,100,12)

In [92]:
a

array([35, 70, 87, 63, 59, 58, 76,  8, 97, 67, 88, 25])

In [93]:
a>50

array([False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False])

In [94]:
(a>50).sum()

9

In [95]:
a[a>50]   #boolean exp as index

array([70, 87, 63, 59, 58, 76, 97, 67, 88])

In [96]:
(a>50) & (a<80)

array([False,  True, False,  True,  True,  True,  True, False, False,
        True, False, False])

In [97]:
a[(a>50) & (a<80)]

array([70, 63, 59, 58, 76, 67])

In [98]:
a[(a>50) & (a<80)]=111 #changing original array elements

In [99]:
a

array([ 35, 111,  87, 111, 111, 111, 111,   8,  97, 111,  88,  25])

### Array Manipulation

In [100]:
np.arange(32).reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [101]:
np.arange(32).reshape(1,32) #1 row, 32 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [102]:
np.arange(32).reshape(32,1) #32 rows, 1 column

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29],
       [30],
       [31]])

In [103]:
np.arange(32).reshape(4,2,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [104]:
np.arange(32).reshape(2,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]]])

In [105]:
np.arange(32).reshape(8,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [107]:
np.arange(32).reshape(-1,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [110]:
print(np.random.randint(1,100,(4,4)))
print(np.random.randint(1,100,(4,4)).reshape(16)) #CONVERTING 2D array into 1D arrayt

[[99 57  8  8]
 [80 47 54 77]
 [87 33 16 83]
 [71 56 65 71]]
[62 73 69 48 37 29 35 63 43 90 83 72 82 67 35 77]


In [114]:
#converting 3D array into 1D array

print(np.random.randint(1,100,(4,2,2)))
print(np.random.randint(1,100,(4,2,2)).flatten())


[[[33 47]
  [28 49]]

 [[32 16]
  [73 32]]

 [[98 99]
  [33 97]]

 [[99 98]
  [41 37]]]
[17 45 91  1  6 30 18 79 91 62 20 53  8 63 51 78]


In [115]:
a=np.array([5,2,3])
print(a)
print(np.expand_dims(a,axis=0))  #2d array , expanding row
print(np.expand_dims(a,axis=1)) #expanding column


[5 2 3]
[[5 2 3]]
[[5]
 [2]
 [3]]


### Mathematical operations



In [116]:
### Add two list elementswise

l1=[1,2,3]
l2=[4,5,6]
list(map(lambda x,y:x+y,l1,l2))


[5, 7, 9]

In [117]:
l1+l2 

[1, 2, 3, 4, 5, 6]

In [118]:
l1*l2

TypeError: can't multiply sequence by non-int of type 'list'

In [120]:
l1*3  #repetition

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [121]:
a1=np.array(l1)
a2=np.array(l2)
a1+a2

array([5, 7, 9])

In [122]:
a1*a2

array([ 4, 10, 18])

In [123]:
a1%a2

array([1, 2, 3], dtype=int32)

In [124]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [125]:
a1//2

array([0, 1, 1], dtype=int32)

In [126]:
print(a1)

[1 2 3]


In [127]:
print(a1+10)  #adding value to each element of array

[11 12 13]


### Array broadcasting rules

* when operating on two arrays, Numpy compares their shapes elements-wise. 
* it starts with the trailing dimension,and works its way forward. 
* 2 dimensions are compared when they are equal , or one of them is 1

In [130]:
a3=np.full((3,4),1)  #smaller one
a4=np.full((2,3,4),2) #larger one
print(a3)
print(a4)
a5=a3-a4

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]

 [[2 2 2 2]
  [2 2 2 2]
  [2 2 2 2]]]


In [131]:
a5

array([[[-1, -1, -1, -1],
        [-1, -1, -1, -1],
        [-1, -1, -1, -1]],

       [[-1, -1, -1, -1],
        [-1, -1, -1, -1],
        [-1, -1, -1, -1]]])

In [132]:
a=np.array([40,50,10,90])
print(np.mean(a))
print(a.mean())
print(np.median(a))
print(a.max())
print(a.min())

47.5
47.5
45.0
90
10


### Vectorize functions

In [133]:
def greater(a,b):
    if a>b:
        return a
    else:
        return b
    

In [134]:
greater(12,34)

34

In [135]:
greater([2,3,98],[54,1,2])

[54, 1, 2]

In [136]:
[2,3,98]>[54,1,2]

False

In [137]:
#element wise comparison

vgreater=np.vectorize(greater)
vgreater([2,3,98],[54,1,2])

array([54,  3, 98])

In [138]:
def exp3(n):
    return 3**n

vexp3=np.vectorize(exp3)

vexp3([1,2,3])

array([ 3,  9, 27])

In [139]:
a=np.array([[3,4],[1,2]])
b=np.eye(2)


In [140]:
a.T

array([[3, 1],
       [4, 2]])

In [141]:
print(a)
print(b)

[[3 4]
 [1 2]]
[[1. 0.]
 [0. 1.]]


In [142]:
a*b #normal multiplication

array([[3., 0.],
       [0., 2.]])

In [143]:
np.dot(a,b) #matrix multiplication

array([[3., 4.],
       [1., 2.]])

In [144]:
a=np.array([40,30,20,10,50])

In [145]:
print(a)
print(np.quantile(a,0.5))  #Median q2
print(np.quantile(a,0.25))  #Median of first half q1
print(np.quantile(a,0.75))  #Median of second half q3

[40 30 20 10 50]
30.0
20.0
40.0


In [146]:
help(np.quantile)

Help on function quantile in module numpy:

quantile(a, q, axis=None, out=None, overwrite_input=False, interpolation='linear', keepdims=False)
    Compute the q-th quantile of the data along the specified axis.
    
    .. versionadded:: 1.15.0
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    q : array_like of float
        Quantile or sequence of quantiles to compute, which must be between
        0 and 1 inclusive.
    axis : {int, tuple of int, None}, optional
        Axis or axes along which the quantiles are computed. The
        default is to compute the quantile(s) along a flattened
        version of the array.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output,
        but the type (of the output) will be cast if necessary.
    overwrite_input : bool, optional
        If True, then allow t

### Logarithemic and exponential

In [147]:
np.log(5)

1.6094379124341003

In [148]:
import math
math.log(5)

1.6094379124341003

In [149]:
np.log2(4)

2.0

In [150]:
np.log([2,3,4,6])

array([0.69314718, 1.09861229, 1.38629436, 1.79175947])

In [151]:
np.log2([2,3,4,5])

array([1.        , 1.5849625 , 2.        , 2.32192809])

In [152]:
np.log(1)

0.0

In [153]:
np.log(10)

2.302585092994046

In [154]:
np.exp2(5) #2 power 5

32.0

In [155]:
np.expm1(2)

6.38905609893065

In [156]:
np.exp(5)-1   #(e power 5-1)(e=2.7)

147.4131591025766

In [157]:
np.exp([2,3,4,5,6])

array([  7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ,
       403.42879349])

### Linear algebra

In [162]:
a=np.array([[3,4],[1,2]])

np.linalg.det(a)  #DETERMINANT OF MATRIX (ad-bc)

2.0000000000000004

In [163]:
print(a)

[[3 4]
 [1 2]]


In [165]:
ia=np.linalg.inv(a)
np.dot(a,ia)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [166]:
np.trace(a)

5